apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets: # delete this if you are not using a private docker repo. If you are, be sure to configure the app-reg-cred file properly or else this will fail.
      - name: app-regcred
      containers:
      - name: app
        image: # your custom image
        imagePullPolicy: Always
        ports:
          - name: client
            containerPort: 3000
          - name: server
            containerPort: 4400
        envFrom:
          - configMapRef:
              name: app-configmap
          - secretRef:
              name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app-client-service
  namespace: app
spec:
  selector:
    app: app
  ports:
    - name: client
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  namespace: app
spec:
  selector:
    app: app
  ports:
    - name: server
      protocol: TCP
      port: 80
      targetPort: 4400
