apiVersion: v1
kind: Secret
metadata:
  name: app-regcred
  namespace: app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # see this: https://www.youtube.com/watch?v=asIS4KIs40M for how to get the proper config string.
# only use this file if you are using a private registry to store your custom app image
